### ISSUE TITLE
OpenCV vs DICe calibration results

### ISSUE THREAD

**Issue by JimmyGitHubFr** [dicengine/dice#222]
Hello,

I am trying to verify my calibration results from DICe with the OpenCV calibration camera code (https://learnopencv.com/camera-calibration-using-opencv/), but for the same images, I get very different results, is it normal?

Also, I find it odd that there is no spacing size to put in the OpenCV calibration, while DICe there is.

Can you help me find what is wrong, or different between these two calibration method, please?

Best regards,

Jimmy

**Comment by dicengine** [comment]
Hi Jimmy, the link you have above is for the single camera calibration in OpenCV, DICe uses the stereo calibration tool. They should both give you similar values for the intrinsic parameters like the focal length and image centers, etc. Can you be more specific about the differences you have observed?

**Comment by dicengine** [comment]
Are you using the default calibration options in DICe? I'm wondering if you have the same options going to both DICe and OpenCV.

**Comment by dicengine** [comment]
I'm still looking into the issue with the checkerboard patterns, but with regards to the feature matching failing on the cross correlation, are you able to share your cal.xml file with a stereo pair of images so I can see why it's failing?

**Comment by dicengine** [comment]
I took a look at the stereo correlation initialization for the images you provided (thanks) and it seems like the calibration may not be very good. Can you upload the calibration images for this case? If I check an epipolar line between the left and right images for points that are easy to identify (for example the corners of the stitched hexagons) using the calibration parameters in your cal.xml file, the points are ten to twenty pixels off the epipolar line suggesting the calibration is not correct.

**Comment by dicengine** [comment]
The average epipolar error is the distance (on average) away from the epipolar line that the corresponding point in the stereo image is. If the calibration is perfect, the corresponding point in the stereo image will be on the epipolar line. It's a simple way to check how good the calibration is.

I'm still looking into what's going on with the cross correlation

**Comment by wvwang** [comment]
Thanks for clarifying the definition of 'avg_epipolar_error'. Is the parameter needed in the cross-correlation?

**Comment by dicengine** [comment]
The 'avg_epipolar_error' parameter is just a diagnostic output from the calibration, it's not used in the cross-correlation.

I've taken another look at your images and there are some other issues that might be causing problems.

- There seems to be a lot of noise in the images. This might be why the initialization is failing
- The speckle size is too small (for the most part on the order of one pixel). For good performance, you need to have your speckels near three pixels in size. If you can't adjust how you apply the pattern, you may consider moving the cameras closer to make the speckles nearly 3 pixels in size.
- There are also issues with either the cameras not being in focus or the shutter speed not being set right causing image blur.

Any one of these three issues could cause bad DIC results and may be why the cross-correlation is failing. It doesn't seem to be the result of any sort of bugs in DICe. If you are able to address the issues with the images above you may notice that even your calibration error improves.

**Comment by dicengine** [comment]
Just an update that the dot target calibration routine in DICe has been substantially updated to address some issues that could have been causing the difference between the native OpenCV calibration and the calibration from the DICe wrapper of OpenCVs cal tool. There were instances of images that could have misidentified two dots in the same location or a small patch of image noise as one of the marker dots from the target pattern. Both of these were almost undetectable from the debugging images in the GUI tool, but could lead to subtle errors in the calibration. The errors weren't large enough to identify a single image to remove from the calibration set to fix the problem. In the latest release https://github.com/dicengine/dice/releases/tag/v3.0-beta.4 this has been fixed so it shouldn't be a problem with releases from this point on.

**Comment by Jascksonyee** [comment]
Hello,@wvwang
  Thanks  you for discussing stereo calibration.

  I have a question about why the calibration of DICe can't read my image when I do calibration, when my image format and naming are the same as the original sample data, but it shows when the folder is empty.

  Can you help me find what is wrong, please?
  Best wishes
  Ting

**Comment by Jascksonyee** [comment]
Thanks for the reply, after asking the question I kept trying and changing, and found that when calibrating, it only reads the left camera, and the problem is that it doesn't fully read my calibration image, I don't know what went wrong.

![d93048985a962f1fe9e6c60770522af](https://user-images.githubusercontent.com/97941882/201812760-cf5fd759-8fda-4844-8a91-a8a98d1ffe7c.png)

**Comment by dicengine** [comment]
DICe might be aborting before reading the right image because the left image failed. Are you sure that the pattern width and height are correct? Looks like you have the correct values for the example image for the checkerboard pattern, but is your actual pattern the same?

**Comment by Jascksonyee** [comment]
Thanka@dicengine
Yes, after I modified it according to my checkerboard, the result is still the same, I wonder if it has a clear requirement for the format in which the image is read? Because in the example the image format is .jpeg, my picture format is also like this, but it is not read, so I am confused.Below are 6 sets of my calibration images.
[dice.zip](https://github.com/dicengine/dice/files/10014156/dice.zip)
![1](https://user-images.githubusercontent.com/97941882/201965049-a769f7c3-8627-4d74-9037-961030c7d3dd.png)

**Comment by dicengine** [comment]
It looks like the calibration is failing only for the first image set which has some sort of speckle pattern background. The rest of the images in the set you posted are reading and calibrating okay for me with DICe version 3-beta.6. The cal images don't have a lot of contrast so that might be introducing a lot of error. Another thing to keep in mind is that the checkerboard pattern is not the greatest for getting an accurate cal. I would use the dot pattern if you are able to.
